### ISSUE TITLE
Create more comprehensive catalog documentation

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/components-catalog#124]
The current documentation is poor and doesn't explain what is the catalog and for what is useful
Tasks:

- [x] Create a new documentation skeleton
- [x] TSDoc the `assets` module
- [x] TSDoc the `accounts` module
- [x] TSDoc the `nevermined` module #106 
- [x] Automate the generation of documentation via TS Doc
- [x] Add a new example to the `example.md` doc
- [x] Review all the documentation
- [ ] Review tutorials to make sure they are working with the latest version of the catalog
